// <auto-generated />
using System;
using LoanOriginationService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanOriginationService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoanOriginationService.Domain.Models.DealReview", b =>
                {
                    b.Property<int>("reviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("reviewId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("createdBy")
                        .HasColumnType("int");

                    b.Property<int>("dealId")
                        .HasColumnType("int");

                    b.Property<string>("decision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("decisionReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("modifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("officerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("reviewDate")
                        .HasColumnType("datetime2");

                    b.HasKey("reviewId");

                    b.HasIndex("dealId");

                    b.ToTable("DealReviews");
                });

            modelBuilder.Entity("LoanOriginationService.Domain.Models.LoanDeals", b =>
                {
                    b.Property<int>("dealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dealId"));

                    b.Property<decimal>("approvedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("cibilScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("createdBy")
                        .HasColumnType("int");

                    b.Property<int>("currentStatus")
                        .HasColumnType("int");

                    b.Property<int>("custId")
                        .HasColumnType("int");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("eligibleAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<int>("loanTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("modifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("riskRating")
                        .HasColumnType("int");

                    b.Property<int>("scorecardId")
                        .HasColumnType("int");

                    b.HasKey("dealId");

                    b.HasIndex("loanTypeId");

                    b.ToTable("LoanDeals");
                });

            modelBuilder.Entity("LoanOriginationService.Domain.Models.LoanTypes", b =>
                {
                    b.Property<int>("loanTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("loanTypeId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("createdBy")
                        .HasColumnType("int");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("loanTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("modifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("loanTypeId");

                    b.ToTable("LoanTypes");
                });

            modelBuilder.Entity("LoanOriginationService.Domain.Models.DealReview", b =>
                {
                    b.HasOne("LoanOriginationService.Domain.Models.LoanDeals", "LoanDeals")
                        .WithMany()
                        .HasForeignKey("dealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoanDeals");
                });

            modelBuilder.Entity("LoanOriginationService.Domain.Models.LoanDeals", b =>
                {
                    b.HasOne("LoanOriginationService.Domain.Models.LoanTypes", "LoanType")
                        .WithMany()
                        .HasForeignKey("loanTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoanType");
                });
#pragma warning restore 612, 618
        }
    }
}
